export interface VideoThumbnail {
  quality: string;
  url: string;
  width: number;
  height: number;
}

export interface VideoStream {
  url: string;
  itag: number;
  type: string;
  quality: string;
  fps?: number;
  container: string;
  encoding: string;
  qualityLabel: string;
  bitrate: number;
  size?: string;
  headers?: Record<string, string>;
}

export interface AudioStream {
  url: string;
  itag: number;
  type: string;
  quality: string;
  bitrate: number;
  container: string;
  encoding: string;
  size?: string;
}

export interface VideoResult {
  videoId: string;
  title: string;
  author: string;
  authorId: string;
  authorUrl: string;
  videoThumbnails: VideoThumbnail[];
  description: string;
  descriptionHtml?: string;
  published: number;
  publishedText: string;
  viewCount: number;
  likeCount?: number;
  lengthSeconds: number;
  paid: boolean;
  premium: boolean;
  liveNow: boolean;
  isUpcoming: boolean;
}

export interface VideoDetail extends VideoResult {
  adaptiveFormats: VideoStream[];
  formatStreams: VideoStream[];
  hlsUrl?: string;
  dashUrl?: string;
  recommendedVideos: VideoResult[];
  authorThumbnails: VideoThumbnail[];
  subCountText: string;
  allowRatings: boolean;
  rating: number;
  isFamilyFriendly: boolean;
  genre: string;
  keywords: string[];
}

export interface ChannelResult {
  authorId: string;
  author: string;
  authorThumbnails: VideoThumbnail[];
  subCount: number;
  videoCount: number;
  description: string;
  autoGenerated: boolean;
}

export interface PlaylistResult {
  playlistId: string;
  title: string;
  author: string;
  authorId: string;
  videoCount: number;
  videos: VideoResult[];
  videoThumbnails: VideoThumbnail[];
}

export type SearchType = 'video' | 'music' | 'channel' | 'playlist';
export type SortOrder = 'relevance' | 'upload_date' | 'view_count' | 'rating';

export interface SearchParams {
  query: string;
  type?: SearchType;
  sort?: SortOrder;
  page?: number;
}

export type DownloadFormat = 'mp4_360p' | 'mp4_720p' | 'mp4_1080p' | 'mp4_4k' | 'mp3_128' | 'mp3_320' | 'flac';
export type DownloadStatus = 'pending' | 'downloading' | 'paused' | 'completed' | 'failed';

export interface DownloadItem {
  id: string;
  videoId: string;
  title: string;
  author: string;
  thumbnail: string;
  format: DownloadFormat;
  filePath: string;
  fileSize: number;
  downloadedBytes: number;
  status: DownloadStatus;
  progress: number;
  timestamp: number;
  errorMessage?: string;
}

export interface LibraryItem {
  id: string;
  videoId: string;
  title: string;
  author: string;
  thumbnail: string;
  lengthSeconds: number;
  watchedAt: number;
  watchProgress?: number;
  type: 'history' | 'liked' | 'saved';
}

export interface PlayerState {
  videoId: string | null;
  title: string;
  author: string;
  thumbnail: string;
  audioUrl?: string;
  audioHeaders?: Record<string, string>;
  isPlaying: boolean;
  isAudioOnly: boolean;
  position: number;
  duration: number;
  quality: string;
}
